create table "public"."address" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "useId" uuid,
    "state" text,
    "address" character varying,
    "phone" text,
    "updatedA_at" timestamp with time zone not null
);


alter table "public"."address" enable row level security;

create table "public"."bookings" (
    "booking_id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "is_team_booking" boolean default false,
    "slot_id" bigint,
    "user_id" uuid,
    "additional_players" json,
    "updatedAt" timestamp with time zone not null,
    "numberOfPlayers" integer,
    "status" text,
    "date_time" timestamp without time zone,
    "duration_minutes" bigint
);


alter table "public"."bookings" enable row level security;

create table "public"."dailySlot" (
    "dailySlotId" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "date" date,
    "totalSlots" integer,
    "updatedAt" timestamp with time zone
);


alter table "public"."dailySlot" enable row level security;

create table "public"."profiles" (
    "id" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "avatar_url" character varying,
    "email" text,
    "name" text,
    "picture" character varying
);


alter table "public"."profiles" enable row level security;

create table "public"."slots" (
    "slotId" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "currentCapacity" integer,
    "dailySlotId" bigint,
    "startTime" timestamp with time zone,
    "endTime" timestamp with time zone,
    "maxCapacity" bigint,
    "updatedAt" timestamp with time zone not null
);


alter table "public"."slots" enable row level security;

CREATE UNIQUE INDEX address_pkey ON public.address USING btree (id);

CREATE UNIQUE INDEX bookings_pkey ON public.bookings USING btree (booking_id);

CREATE UNIQUE INDEX "dailySlot_pkey" ON public."dailySlot" USING btree ("dailySlotId");

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX slots_pkey ON public.slots USING btree ("slotId");

alter table "public"."address" add constraint "address_pkey" PRIMARY KEY using index "address_pkey";

alter table "public"."bookings" add constraint "bookings_pkey" PRIMARY KEY using index "bookings_pkey";

alter table "public"."dailySlot" add constraint "dailySlot_pkey" PRIMARY KEY using index "dailySlot_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."slots" add constraint "slots_pkey" PRIMARY KEY using index "slots_pkey";

alter table "public"."address" add constraint "address_useId_fkey" FOREIGN KEY ("useId") REFERENCES profiles(id) ON UPDATE CASCADE not valid;

alter table "public"."address" validate constraint "address_useId_fkey";

alter table "public"."bookings" add constraint "bookings_slot_id_fkey" FOREIGN KEY (slot_id) REFERENCES slots("slotId") ON UPDATE CASCADE not valid;

alter table "public"."bookings" validate constraint "bookings_slot_id_fkey";

alter table "public"."bookings" add constraint "bookings_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON UPDATE CASCADE not valid;

alter table "public"."bookings" validate constraint "bookings_user_id_fkey";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON UPDATE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."slots" add constraint "slots_dailySlotId_fkey" FOREIGN KEY ("dailySlotId") REFERENCES "dailySlot"("dailySlotId") ON UPDATE CASCADE not valid;

alter table "public"."slots" validate constraint "slots_dailySlotId_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.create_user_profile()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$begin
  insert into public.profiles (id, name, email, avatar_url,picture)
  values (
    new.id,
    new.raw_user_meta_data->'name',
    new.raw_user_meta_data->'email',
    new.raw_user_meta_data->'avatar_url',
    new.raw_user_meta_data->'picture'
  );
  return new;
end;$function$
;

grant delete on table "public"."address" to "anon";

grant insert on table "public"."address" to "anon";

grant references on table "public"."address" to "anon";

grant select on table "public"."address" to "anon";

grant trigger on table "public"."address" to "anon";

grant truncate on table "public"."address" to "anon";

grant update on table "public"."address" to "anon";

grant delete on table "public"."address" to "authenticated";

grant insert on table "public"."address" to "authenticated";

grant references on table "public"."address" to "authenticated";

grant select on table "public"."address" to "authenticated";

grant trigger on table "public"."address" to "authenticated";

grant truncate on table "public"."address" to "authenticated";

grant update on table "public"."address" to "authenticated";

grant delete on table "public"."address" to "service_role";

grant insert on table "public"."address" to "service_role";

grant references on table "public"."address" to "service_role";

grant select on table "public"."address" to "service_role";

grant trigger on table "public"."address" to "service_role";

grant truncate on table "public"."address" to "service_role";

grant update on table "public"."address" to "service_role";

grant delete on table "public"."bookings" to "anon";

grant insert on table "public"."bookings" to "anon";

grant references on table "public"."bookings" to "anon";

grant select on table "public"."bookings" to "anon";

grant trigger on table "public"."bookings" to "anon";

grant truncate on table "public"."bookings" to "anon";

grant update on table "public"."bookings" to "anon";

grant delete on table "public"."bookings" to "authenticated";

grant insert on table "public"."bookings" to "authenticated";

grant references on table "public"."bookings" to "authenticated";

grant select on table "public"."bookings" to "authenticated";

grant trigger on table "public"."bookings" to "authenticated";

grant truncate on table "public"."bookings" to "authenticated";

grant update on table "public"."bookings" to "authenticated";

grant delete on table "public"."bookings" to "service_role";

grant insert on table "public"."bookings" to "service_role";

grant references on table "public"."bookings" to "service_role";

grant select on table "public"."bookings" to "service_role";

grant trigger on table "public"."bookings" to "service_role";

grant truncate on table "public"."bookings" to "service_role";

grant update on table "public"."bookings" to "service_role";

grant delete on table "public"."dailySlot" to "anon";

grant insert on table "public"."dailySlot" to "anon";

grant references on table "public"."dailySlot" to "anon";

grant select on table "public"."dailySlot" to "anon";

grant trigger on table "public"."dailySlot" to "anon";

grant truncate on table "public"."dailySlot" to "anon";

grant update on table "public"."dailySlot" to "anon";

grant delete on table "public"."dailySlot" to "authenticated";

grant insert on table "public"."dailySlot" to "authenticated";

grant references on table "public"."dailySlot" to "authenticated";

grant select on table "public"."dailySlot" to "authenticated";

grant trigger on table "public"."dailySlot" to "authenticated";

grant truncate on table "public"."dailySlot" to "authenticated";

grant update on table "public"."dailySlot" to "authenticated";

grant delete on table "public"."dailySlot" to "service_role";

grant insert on table "public"."dailySlot" to "service_role";

grant references on table "public"."dailySlot" to "service_role";

grant select on table "public"."dailySlot" to "service_role";

grant trigger on table "public"."dailySlot" to "service_role";

grant truncate on table "public"."dailySlot" to "service_role";

grant update on table "public"."dailySlot" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."slots" to "anon";

grant insert on table "public"."slots" to "anon";

grant references on table "public"."slots" to "anon";

grant select on table "public"."slots" to "anon";

grant trigger on table "public"."slots" to "anon";

grant truncate on table "public"."slots" to "anon";

grant update on table "public"."slots" to "anon";

grant delete on table "public"."slots" to "authenticated";

grant insert on table "public"."slots" to "authenticated";

grant references on table "public"."slots" to "authenticated";

grant select on table "public"."slots" to "authenticated";

grant trigger on table "public"."slots" to "authenticated";

grant truncate on table "public"."slots" to "authenticated";

grant update on table "public"."slots" to "authenticated";

grant delete on table "public"."slots" to "service_role";

grant insert on table "public"."slots" to "service_role";

grant references on table "public"."slots" to "service_role";

grant select on table "public"."slots" to "service_role";

grant trigger on table "public"."slots" to "service_role";

grant truncate on table "public"."slots" to "service_role";

grant update on table "public"."slots" to "service_role";


